# syntax=docker/dockerfile:1

FROM node:16-alpine

ENV NODE_ENV=production
ENV REDIS=redis://redis:6379
ENV RYUK_URL=http://ryuk
ENV SHINGO_URL=http://shingo

COPY ["package.json", "package-lock.json", "./"]
RUN npm ci

COPY consumer consumer/

CMD ["node", "consumer/index.js"]
