# syntax=docker/dockerfile:1

FROM node:16-alpine

ENV NODE_ENV=production
ENV REDIS=redis://redis:6379
ENV PORT=3000
ENV DASHBOARD_LOGIN=admin
ENV DASHBOARD_PASSWORD=password
EXPOSE 3000

COPY ["package.json", "package-lock.json", "./"]
RUN npm ci

COPY dashboard dashboard/

CMD ["node", "dashboard/index.js"]
