version: "3.9"

services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    env_file: ./.env
    ports:
      - "3000:3000"
    depends_on:
      - redis

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    env_file: ./.env
    ports:
      - "4000:3000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    entrypoint: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis-data:/data

volumes:
  redis-data:
