# syntax=docker/dockerfile:1

FROM node:16-alpine

ENV NODE_ENV=production
ENV REDIS=redis://redis:6379
ENV MONGO=mongodb://mongodb:27017
ENV PORT=3000
EXPOSE 3000

COPY ["package.json", "package-lock.json", "./"]
RUN npm ci

COPY producer producer/

CMD ["node", "producer/index.js"]
