# syntax=docker/dockerfile:1

FROM node:lts-alpine

ENV NODE_ENV=production
ENV REDIS=redis://redis:6379
ENV PORT=3000
EXPOSE 3000

COPY ["package.json", "package-lock.json", "./"]
RUN npm ci

COPY . .

CMD ["node", "producer/index.js"]
