version: "3.9"

services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    env_file: ./.env
    ports:
      - "6234:3000"
    depends_on:
      - redis

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    env_file: ./.env
    depends_on:
      - producer

  listener:
    build:
      context: .
      dockerfile: Dockerfile.listener
    env_file: ./.env
    depends_on:
      - consumer
      - mongodb

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    env_file: ./.env
    ports:
      - "4000:3000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    entrypoint: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis-data:/data

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  redis-data:
  mongodb-data:
